import type { CaseStudy } from "@/lib/caseStudyContent";
import type { Fundamental } from "@/lib/caseStudyFundamentals";
import { LAW_CIVIL_LITIGATION_CASES, LAW_CIVIL_LITIGATION_FUNDAMENTALS } from "@/lib/cases/law-civil-litigation";
import { LAW_CONSTITUTIONAL_REGULATORY_CASES, LAW_CONSTITUTIONAL_REGULATORY_FUNDAMENTALS } from "@/lib/cases/law-constitutional-regulatory";
import { LAW_CONTRACT_LAW_CASES, LAW_CONTRACT_LAW_FUNDAMENTALS } from "@/lib/cases/law-contract-law";
import { LAW_CORPORATE_COMPLIANCE_CASES, LAW_CORPORATE_COMPLIANCE_FUNDAMENTALS } from "@/lib/cases/law-corporate-compliance";
import { LAW_CRIMINAL_LAW_CASES, LAW_CRIMINAL_LAW_FUNDAMENTALS } from "@/lib/cases/law-criminal-law";
import { LAW_TORTS_CIVIL_LIABILITY_CASES, LAW_TORTS_CIVIL_LIABILITY_FUNDAMENTALS } from "@/lib/cases/law-torts-civil-liability";
import { LAW_ADMINISTRATIVE_LAW_CASES, LAW_ADMINISTRATIVE_LAW_FUNDAMENTALS } from "@/lib/cases/law-administrative-law";
import { LAW_PROPERTY_LAW_CASES, LAW_PROPERTY_LAW_FUNDAMENTALS } from "@/lib/cases/law-property-law";
import { LAW_LABOR_EMPLOYMENT_CASES, LAW_LABOR_EMPLOYMENT_FUNDAMENTALS } from "@/lib/cases/law-labor-employment";
import { LAW_FAMILY_LAW_CASES, LAW_FAMILY_LAW_FUNDAMENTALS } from "@/lib/cases/law-family-law";
import { LAW_TAX_LAW_CASES, LAW_TAX_LAW_FUNDAMENTALS } from "@/lib/cases/law-tax-law";
import { POLITICS_CAMPAIGN_STRATEGY_CASES, POLITICS_CAMPAIGN_STRATEGY_FUNDAMENTALS } from "@/lib/cases/politics-campaign-strategy";
import { POLITICS_CRISIS_RESPONSE_CASES, POLITICS_CRISIS_RESPONSE_FUNDAMENTALS } from "@/lib/cases/politics-crisis-response";
import { POLITICS_DOMESTIC_POLICY_CASES, POLITICS_DOMESTIC_POLICY_FUNDAMENTALS } from "@/lib/cases/politics-domestic-policy";
import { POLITICS_FOREIGN_POLICY_DIPLOMACY_CASES, POLITICS_FOREIGN_POLICY_DIPLOMACY_FUNDAMENTALS } from "@/lib/cases/politics-foreign-policy-diplomacy";
import { POLITICS_LEGISLATIVE_NEGOTIATION_CASES, POLITICS_LEGISLATIVE_NEGOTIATION_FUNDAMENTALS } from "@/lib/cases/politics-legislative-negotiation";
import { POLITICS_PUBLIC_ADMINISTRATION_CASES, POLITICS_PUBLIC_ADMINISTRATION_FUNDAMENTALS } from "@/lib/cases/politics-public-administration";
import { POLITICS_ECONOMIC_FISCAL_POLICY_CASES, POLITICS_ECONOMIC_FISCAL_POLICY_FUNDAMENTALS } from "@/lib/cases/politics-economic-fiscal-policy";
import { POLITICS_INTERNATIONAL_INSTITUTIONS_CASES, POLITICS_INTERNATIONAL_INSTITUTIONS_FUNDAMENTALS } from "@/lib/cases/politics-international-institutions";
import { POLITICS_COMMUNICATION_MEDIA_CASES, POLITICS_COMMUNICATION_MEDIA_FUNDAMENTALS } from "@/lib/cases/politics-communication-media";
import { POLITICS_ELECTORAL_SYSTEMS_CASES, POLITICS_ELECTORAL_SYSTEMS_FUNDAMENTALS } from "@/lib/cases/politics-electoral-systems";
import { POLITICS_LOCAL_REGIONAL_GOVERNMENT_CASES, POLITICS_LOCAL_REGIONAL_GOVERNMENT_FUNDAMENTALS } from "@/lib/cases/politics-local-regional-government";

/** Law and Politics case banks, one file per category. */
export const COUNTRY_BOUND_CASES: CaseStudy[] = [
  ...LAW_CIVIL_LITIGATION_CASES,
  ...LAW_CONSTITUTIONAL_REGULATORY_CASES,
  ...LAW_CONTRACT_LAW_CASES,
  ...LAW_CORPORATE_COMPLIANCE_CASES,
  ...LAW_CRIMINAL_LAW_CASES,
  ...LAW_TORTS_CIVIL_LIABILITY_CASES,
  ...LAW_ADMINISTRATIVE_LAW_CASES,
  ...LAW_PROPERTY_LAW_CASES,
  ...LAW_LABOR_EMPLOYMENT_CASES,
  ...LAW_FAMILY_LAW_CASES,
  ...LAW_TAX_LAW_CASES,
  ...POLITICS_CAMPAIGN_STRATEGY_CASES,
  ...POLITICS_CRISIS_RESPONSE_CASES,
  ...POLITICS_DOMESTIC_POLICY_CASES,
  ...POLITICS_FOREIGN_POLICY_DIPLOMACY_CASES,
  ...POLITICS_LEGISLATIVE_NEGOTIATION_CASES,
  ...POLITICS_PUBLIC_ADMINISTRATION_CASES,
  ...POLITICS_ECONOMIC_FISCAL_POLICY_CASES,
  ...POLITICS_INTERNATIONAL_INSTITUTIONS_CASES,
  ...POLITICS_COMMUNICATION_MEDIA_CASES,
  ...POLITICS_ELECTORAL_SYSTEMS_CASES,
  ...POLITICS_LOCAL_REGIONAL_GOVERNMENT_CASES,
];

/** Law and Politics fundamentals, keyed "profession/category" like FUNDAMENTALS. */
export const COUNTRY_BOUND_FUNDAMENTALS: Record<string, Fundamental[]> = {
  "law/Civil Litigation": LAW_CIVIL_LITIGATION_FUNDAMENTALS,
  "law/Constitutional & Regulatory": LAW_CONSTITUTIONAL_REGULATORY_FUNDAMENTALS,
  "law/Contract Law": LAW_CONTRACT_LAW_FUNDAMENTALS,
  "law/Corporate & Compliance": LAW_CORPORATE_COMPLIANCE_FUNDAMENTALS,
  "law/Criminal Law": LAW_CRIMINAL_LAW_FUNDAMENTALS,
  "law/Torts & Civil Liability": LAW_TORTS_CIVIL_LIABILITY_FUNDAMENTALS,
  "law/Administrative Law": LAW_ADMINISTRATIVE_LAW_FUNDAMENTALS,
  "law/Property Law": LAW_PROPERTY_LAW_FUNDAMENTALS,
  "law/Labor & Employment Law": LAW_LABOR_EMPLOYMENT_FUNDAMENTALS,
  "law/Family Law": LAW_FAMILY_LAW_FUNDAMENTALS,
  "law/Tax Law": LAW_TAX_LAW_FUNDAMENTALS,
  "politics/Campaign Strategy": POLITICS_CAMPAIGN_STRATEGY_FUNDAMENTALS,
  "politics/Crisis Response": POLITICS_CRISIS_RESPONSE_FUNDAMENTALS,
  "politics/Domestic Policy": POLITICS_DOMESTIC_POLICY_FUNDAMENTALS,
  "politics/Foreign Policy & Diplomacy": POLITICS_FOREIGN_POLICY_DIPLOMACY_FUNDAMENTALS,
  "politics/Legislative Negotiation": POLITICS_LEGISLATIVE_NEGOTIATION_FUNDAMENTALS,
  "politics/Public Administration & Governance": POLITICS_PUBLIC_ADMINISTRATION_FUNDAMENTALS,
  "politics/Economic & Fiscal Policy": POLITICS_ECONOMIC_FISCAL_POLICY_FUNDAMENTALS,
  "politics/International & Regional Institutions": POLITICS_INTERNATIONAL_INSTITUTIONS_FUNDAMENTALS,
  "politics/Political Communication & Media": POLITICS_COMMUNICATION_MEDIA_FUNDAMENTALS,
  "politics/Electoral Systems & Law": POLITICS_ELECTORAL_SYSTEMS_FUNDAMENTALS,
  "politics/Local & Regional Government": POLITICS_LOCAL_REGIONAL_GOVERNMENT_FUNDAMENTALS,
};
