export interface Fundamental {
  id: string;
  label: string;
}

/**
 * The checklist of fundamental knowledge points for each category — "what a
 * competent professional in this area should be able to handle." Every
 * fundamental should be covered by at least one case's `testsFundamentals`
 * (a case can cover more than one; coverage is flexible, not strict 1:1).
 * Keyed by "profession/category" so law/politics can be added later without
 * colliding with business category names.
 */
export const FUNDAMENTALS: Record<string, Fundamental[]> = {
  "business/Strategy": [
    { id: "strat-five-forces", label: "Applying Porter's Five Forces to assess industry attractiveness and competitive intensity" },
    { id: "strat-generic-strategies", label: "Choosing among cost leadership, differentiation, and focus (Porter's generic strategies)" },
    { id: "strat-resource-based-view", label: "Identifying core competencies/VRIN resources as the basis of sustainable competitive advantage" },
    { id: "strat-diversification-related-unrelated", label: "Evaluating related vs. unrelated diversification and capability transferability" },
    { id: "strat-vertical-integration-make-buy", label: "Deciding vertical integration vs. make-vs-buy using transaction cost economics" },
    { id: "strat-build-buy-partner", label: "Choosing organic growth (build) vs. acquisition (buy) vs. alliance/partnership to gain a capability" },
    { id: "strat-ma-integration-risk", label: "Assessing M&A integration risk (cultural fit, talent retention, synergy realization)" },
    { id: "strat-blue-ocean-value-innovation", label: "Using blue ocean strategy / value curve analysis to escape head-to-head competition" },
    { id: "strat-disruption-theory", label: "Recognizing disruptive innovation dynamics and the incumbent's dilemma responding to low-cost entrants" },
    { id: "strat-portfolio-bcg", label: "Applying portfolio frameworks (BCG growth-share matrix) to allocate capital across business units" },
    { id: "strat-harvest-divest-exit", label: "Deciding whether to harvest, divest, or wind down a declining business unit" },
    { id: "strat-sku-portfolio-rationalization", label: "Rationalizing a product/SKU portfolio using contribution margin and complexity-cost analysis" },
    { id: "strat-market-entry-mode", label: "Selecting international market entry mode and sequencing (CAGE distance, Uppsala model)" },
    { id: "strat-platform-ecosystem-lockin", label: "Analyzing platform/ecosystem strategy, network effects, and switching-cost-based competitive threats" },
    { id: "strat-competitive-dynamics-game-theory", label: "Applying game theory to anticipate competitor response (capacity moves, price wars, signaling)" },
    { id: "strat-real-options-strategic-investment", label: "Using real options thinking to sequence and de-risk strategic bets under uncertainty" },
    { id: "strat-nonmarket-regulatory-strategy", label: "Incorporating regulatory/non-market risk into strategic decision-making" },
    { id: "strat-scenario-planning", label: "Using scenario planning to stress-test a strategy against multiple plausible futures" },
    { id: "strat-strategy-execution-alignment", label: "Aligning organizational structure, incentives, and culture with a chosen strategy (execution, not just design)" },
    { id: "strat-brand-portfolio-architecture", label: "Structuring brand architecture (sub-brands, brand extension) to support portfolio/segment strategy" },
  ],
  "business/Finance": [
    { id: "fin-npv-irr-payback", label: "Capital budgeting criteria: NPV, IRR, and payback period, and what to do when they disagree" },
    { id: "fin-capital-structure-leverage", label: "Capital structure decisions: debt vs. equity financing, leverage ratios, and debt capacity" },
    { id: "fin-wacc-cost-of-capital", label: "Cost of capital / WACC and risk-adjusted discount rate selection" },
    { id: "fin-cash-conversion-cycle", label: "Cash conversion cycle and distinguishing profitability from liquidity/solvency" },
    { id: "fin-working-capital-financing", label: "Short-term financing tools: invoice factoring, lines of credit, renegotiating payment terms" },
    { id: "fin-fx-risk-hedging", label: "Foreign exchange transaction exposure and hedging strategy (forwards, natural hedges)" },
    { id: "fin-payout-policy-signaling", label: "Dividend policy vs. share buybacks and the signaling effects of payout decisions" },
    { id: "fin-ipo-readiness", label: "IPO readiness and public vs. private capital-raising tradeoffs" },
    { id: "fin-activist-investor-valuation", label: "Responding to activist investors: sum-of-the-parts valuation and conglomerate discount analysis" },
    { id: "fin-unit-economics-burn-runway", label: "Unit economics, burn rate, and runway math for growth-stage capital planning" },
    { id: "fin-lease-vs-buy", label: "Lease-vs-buy/build analysis including balance-sheet and accounting treatment (e.g. ASC 842)" },
    { id: "fin-credit-rating-covenants", label: "Credit ratings, debt covenants, and the cost/contract implications of a downgrade" },
    { id: "fin-margin-pricing-discipline", label: "Gross margin management and pricing/discounting discipline, including sales incentive alignment" },
    { id: "fin-sunk-cost-opportunity-cost", label: "Sunk cost fallacy vs. opportunity cost in resource-allocation decisions" },
    { id: "fin-financial-statement-analysis", label: "Diagnosing a business problem from financial statements (income statement, balance sheet, cash flow)" },
    { id: "fin-break-even-contribution-margin", label: "Break-even analysis and contribution margin in cost/pricing decisions" },
    { id: "fin-valuation-methods", label: "Valuation methods: DCF, trading comparables, precedent transactions" },
    { id: "fin-ma-deal-structuring", label: "M&A deal structuring: consideration mix, earnouts, financing the deal" },
    { id: "fin-capital-allocation-constraints", label: "Allocating scarce capital across competing projects under a binding constraint (e.g. debt service, strategic need)" },
  ],
  "business/Marketing": [
    { id: "mktg-stp-segmentation-targeting-positioning", label: "Segmentation, targeting, and positioning (STP) to identify and prioritize customer segments" },
    { id: "mktg-brand-equity-management", label: "Measuring and protecting brand equity/trust as a strategic asset" },
    { id: "mktg-brand-extension-dilution", label: "Brand extension and sub-branding: when to stretch a brand vs. create a new one to avoid dilution" },
    { id: "mktg-crisis-trust-repair", label: "Crisis communication and trust-repair strategy after a reputational or safety event" },
    { id: "mktg-product-cannibalization", label: "Diagnosing product cannibalization using net revenue/LTV effects, not just the headline substitution rate" },
    { id: "mktg-value-based-pricing", label: "Value-based pricing and price discrimination/tiering strategy" },
    { id: "mktg-freemium-plg-conversion", label: "Freemium conversion and product-led growth funnel design" },
    { id: "mktg-competitive-response-share-vs-profit", label: "Market share vs. profitability tradeoffs and anticipating competitive response to promotions" },
    { id: "mktg-omnichannel-strategy", label: "Omnichannel strategy and managing channel conflict between digital and physical/legacy channels" },
    { id: "mktg-influencer-marketing-brand-safety", label: "Influencer marketing strategy and brand-safety risk management" },
    { id: "mktg-cultural-adaptation-glocalization", label: "Cultural adaptation (\"glocalization\") in international marketing" },
    { id: "mktg-real-time-reactive-marketing", label: "Real-time/reactive marketing and social-media moment management" },
    { id: "mktg-premium-positioning-defense", label: "Defending premium positioning against a credible low-cost competitor" },
    { id: "mktg-data-privacy-ethical-marketing", label: "Navigating data privacy and ethical limits in targeted marketing beyond legal compliance" },
    { id: "mktg-generational-brand-repositioning", label: "Repositioning a brand for a new generational segment without alienating the existing base" },
    { id: "mktg-clv-cac-economics", label: "Customer lifetime value (CLV) and customer acquisition cost (CAC) as marketing investment metrics" },
    { id: "mktg-marketing-mix-4ps", label: "Applying the marketing mix (product, price, place, promotion) to a go-to-market decision" },
    { id: "mktg-new-product-launch-gtm", label: "New product launch / go-to-market strategy, sequencing, and timing" },
    { id: "mktg-integrated-marketing-campaign", label: "Designing an integrated marketing communications campaign across channels" },
  ],
  "business/Operations": [
    { id: "ops-capacity-planning-uncertainty", label: "Making capacity/capital investment decisions under demand-forecast uncertainty (phased or real-options approaches vs. committing to a single forecast)" },
    { id: "ops-supply-risk-mitigation", label: "Distinguishing safety-stock buffering from dual-sourcing/supplier diversification as complementary supply-risk mitigations" },
    { id: "ops-make-vs-buy-tco", label: "Evaluating outsourcing/make-vs-buy decisions on total cost of ownership, not headline savings alone" },
    { id: "ops-quality-scaling", label: "Scaling quality-assurance and testing infrastructure in step with production or revenue growth" },
    { id: "ops-recall-thresholds", label: "Setting recall or stop-production thresholds under incomplete safety evidence (the precautionary principle)" },
    { id: "ops-lean-change-management", label: "Implementing lean/kaizen programs through frontline participation rather than top-down imposition" },
    { id: "ops-automation-workforce-transition", label: "Structuring automation-driven workforce transitions (retraining, severance, phasing) alongside the ROI case" },
    { id: "ops-facility-rationalization", label: "Facility consolidation/closure analysis covering capacity utilization, contractual notice obligations, and community/stakeholder impact" },
    { id: "ops-tech-implementation-cutover", label: "Managing major systems/technology implementation risk, including cutover strategy and rollback decision gates" },
    { id: "ops-variable-demand-capacity", label: "Matching staffing and capacity strategy to variable or seasonal demand (contingent labor vs. automation vs. permanent headcount)" },
    { id: "ops-labor-relations-negotiation", label: "Collective bargaining and labor negotiations that weigh safety/working-condition data against output and contract risk" },
    { id: "ops-safety-culture-accountability", label: "Root-cause safety accountability and escalation culture (Just Culture) when known hazards go unaddressed" },
    { id: "ops-root-cause-analysis", label: "Applying structured root-cause methodology (5 Whys, fishbone) to distinguish systemic causes from one-off events" },
    { id: "ops-vendor-sla-accountability", label: "Designing and enforcing vendor/supplier SLAs and holding vendors accountable for commitments" },
    { id: "ops-regulatory-compliance-ops", label: "Navigating operations-specific regulatory compliance obligations (OSHA, CPSC, WARN Act, FDA recall classes)" },
    { id: "ops-business-continuity-planning", label: "Building and activating business continuity plans for operational disruption, including single points of failure" },
    { id: "ops-bottleneck-throughput-analysis", label: "Identifying and resolving the true constraint/bottleneck in a production or fulfillment system (Theory of Constraints)" },
    { id: "ops-inventory-jit-tradeoffs", label: "Weighing just-in-time/lean inventory savings against the carrying-cost vs. stockout/disruption-risk trade-off" },
  ],
  "business/Leadership & HR": [
    { id: "hr-toxic-high-performer-management", label: "Recognizing and acting on a toxic high-performer's behavior absent a formal complaint" },
    { id: "hr-performance-management-documentation", label: "Applying formal performance-management and documentation practices for behavioral (not just output) issues" },
    { id: "hr-workforce-reduction-tradeoffs", label: "Weighing layoffs vs. across-the-board pay cuts vs. hybrid reduction approaches and their different organizational costs" },
    { id: "hr-survivor-syndrome", label: "Recognizing survivor syndrome after layoffs and what mitigates it" },
    { id: "hr-post-merger-culture-integration", label: "Cultural due diligence and integration risk in M&A, balancing autonomy against process standardization" },
    { id: "hr-succession-planning-interim-leadership", label: "Succession planning and interim leadership arrangements during a sudden, unplanned departure" },
    { id: "hr-dei-program-design-resistance", label: "Designing and defending DEI initiatives against resistance using outcome data rather than dismissing all pushback" },
    { id: "hr-hybrid-rto-policy-design", label: "Designing hybrid/return-to-office policy that balances stated culture goals against real attrition risk" },
    { id: "hr-merit-based-promotion-conflict-of-interest", label: "Making merit-based promotion decisions and managing personal conflicts of interest transparently" },
    { id: "hr-whistleblower-executive-fiduciary-duty", label: "Handling whistleblower reports involving executives under fiduciary and governance obligations" },
    { id: "hr-remote-talent-strategy-investor-pressure", label: "Defending a remote/talent operating model against external (investor) pressure using business rationale, not optics" },
    { id: "hr-executive-compensation-optics", label: "Managing executive-compensation disclosure optics and pay-equity perception amid workforce cuts" },
    { id: "hr-reskilling-workforce-transition", label: "Designing reskilling/upskilling programs with realistic capacity limits and off-ramps for workers who can't transition" },
    { id: "hr-burnout-sustainable-performance", label: "Treating burnout/attrition as a leading indicator and addressing it with structural, not just wellness, interventions" },
    { id: "hr-employee-value-proposition-retention", label: "Diagnosing attrition risk and protecting the employee value proposition through a major policy change" },
    { id: "hr-difficult-conversations-feedback", label: "Delivering difficult conversations (passed-over promotion, hard feedback) honestly rather than hiding behind process language" },
    { id: "hr-labor-employment-law-compliance", label: "Applying core employment-law obligations (WARN Act, notice periods, documentation) to workforce decisions" },
    { id: "hr-psychological-safety-team-culture", label: "Building and protecting psychological safety in a team under stress or after a difficult event" },
    { id: "hr-organizational-culture-change-management", label: "Leading organizational culture change through structured change-management approaches rather than force or decree" },
    { id: "hr-recruitment-selection-bias", label: "Designing structured, bias-resistant hiring/selection processes and recognizing disparate-impact risk in ad hoc criteria" },
  ],
  "business/Crisis Management": [
    { id: "crisis-disclosure-timing", label: "Deciding when to disclose bad news (legal minimum vs. reputational optimum) rather than waiting for a forced disclosure" },
    { id: "crisis-precautionary-principle", label: "Acting under incomplete or inconclusive evidence when safety or reputational risk is asymmetric" },
    { id: "crisis-independent-investigation", label: "Ensuring investigation independence when the accused is senior, powerful, or well-connected" },
    { id: "crisis-duty-of-care", label: "Prioritizing duty of care to victims, employees, or customers ahead of business or legal considerations" },
    { id: "crisis-business-continuity-disruption", label: "Activating business continuity plans following a physical, operational, or cyber disruption" },
    { id: "crisis-employee-safety-first-sequencing", label: "Sequencing crisis decisions with human/employee safety as the explicit first priority" },
    { id: "crisis-whistleblower-protection", label: "Protecting whistleblowers from retaliation while still investigating their claims credibly" },
    { id: "crisis-social-media-response-speed", label: "Balancing response speed against accuracy in a fast-moving social media crisis" },
    { id: "crisis-apology-accountability-framing", label: "Applying image-repair/apology strategy — genuine accountability versus defensive over-explanation" },
    { id: "crisis-ransom-extortion-decision", label: "Structuring decisions under extortion/ransom demands using law-enforcement guidance and risk framing, not gut instinct" },
    { id: "crisis-regulatory-breach-notification", label: "Meeting regulatory breach-notification obligations (HIPAA, GDPR, state law) as distinct from the PR response" },
    { id: "crisis-public-dispute-narrative-control", label: "Responding to a public reputational attack (customer, activist, media) without an inflammatory public fight" },
    { id: "crisis-investor-relations-disclosure", label: "Managing investor relations and public-company disclosure obligations during an active crisis" },
    { id: "crisis-rebuttal-fact-verification", label: "Distinguishing true from false allegations and calibrating rebuttal speed against verification accuracy" },
    { id: "crisis-supply-chain-contingency", label: "Activating parallel-track contingency measures when a critical supplier or partner fails suddenly" },
    { id: "crisis-third-party-supplier-accountability", label: "Taking accountability for safety or compliance failures at third-party/overseas suppliers or partners" },
    { id: "crisis-brand-ip-protection", label: "Protecting brand and intellectual property against counterfeit or bad-actor threats that endanger customers" },
    { id: "crisis-post-crisis-remediation", label: "Designing concrete remediation or restitution commitments, not just words, once a crisis is acknowledged" },
    { id: "crisis-preparedness-playbook", label: "Building a crisis-management protocol and escalation structure proactively, before a real crisis forces one" },
  ],
  "business/Mergers & Acquisitions": [
    { id: "ma-hostile-defense-tactics", label: "Evaluating takeover defenses (poison pills, staggered boards, white knights) and their legal limits" },
    { id: "ma-fiduciary-duty-standards", label: "Applying fiduciary duty standards (Revlon/Unocal) to board decisions under acquisition pressure" },
    { id: "ma-valuation-methods", label: "Applying core valuation methods (DCF, comparable companies, precedent transactions) to a deal" },
    { id: "ma-earnout-structuring", label: "Structuring earnouts and contingent consideration to bridge a valuation gap" },
    { id: "ma-earnout-good-faith-covenants", label: "Drafting and enforcing earnout operating covenants and the implied covenant of good faith post-close" },
    { id: "ma-synergy-quantification", label: "Quantifying and stress-testing revenue/cost synergies before committing to a price" },
    { id: "ma-post-merger-integration-planning", label: "Sequencing post-merger integration and prioritizing customer-facing risk over back-office work" },
    { id: "ma-cultural-due-diligence", label: "Conducting cultural due diligence as a distinct workstream from financial/legal diligence" },
    { id: "ma-talent-retention-in-deals", label: "Designing retention plans for key acquired talent through and after close" },
    { id: "ma-divestiture-decision-analysis", label: "Evaluating a divestiture decision with sunk-cost discipline and stakeholder impact" },
    { id: "ma-antitrust-regulatory-strategy", label: "Navigating antitrust review — second requests, divestiture remedies, consent decrees vs. litigation" },
    { id: "ma-breakup-fee-economics", label: "Weighing breakup fees and walk-away economics in deal risk decisions" },
    { id: "ma-competitive-bidding-discipline", label: "Maintaining walk-away discipline and avoiding the winner's curse in competitive bidding" },
    { id: "ma-strategic-vs-financial-buyer-dynamics", label: "Distinguishing strategic-buyer synergy premiums from financial-buyer pricing logic" },
    { id: "ma-minority-investment-structuring", label: "Structuring minority-stake governance rights (board observer, ROFR, information rights) without control" },
    { id: "ma-spinoff-value-analysis", label: "Evaluating spin-off value creation against the conglomerate discount and separation costs" },
    { id: "ma-lbo-capital-structure", label: "Sizing LBO leverage and covenant headroom against downside/cyclical risk" },
    { id: "ma-spac-mechanics", label: "Understanding SPAC/de-SPAC mechanics — sponsor promote, PIPE financing, redemption risk" },
    { id: "ma-rep-warranty-indemnification", label: "Negotiating representations, warranties, indemnification caps/baskets, and R&W insurance" },
    { id: "ma-cross-border-cfius", label: "Assessing cross-border deal regulatory risk, including CFIUS/national-security review" },
  ],
  "business/Entrepreneurship & Startups": [
    { id: "startup-pmf-signal-validation", label: "Distinguishing a genuine product-market fit signal from noise before acting on it" },
    { id: "startup-mvp-testing", label: "Designing a cheap, fast MVP or landing-page test to validate a hypothesis before committing" },
    { id: "startup-runway-math", label: "Calculating runway and burn multiple, and translating cash position into decision deadlines" },
    { id: "startup-unit-economics", label: "Analyzing CAC, LTV, and contribution margin to judge a path to profitability" },
    { id: "startup-cost-cutting-prioritization", label: "Prioritizing targeted vs. broad cost cuts against a specific milestone" },
    { id: "startup-fundraising-tradeoffs", label: "Weighing venture capital against bootstrapping — dilution, control, and growth capital" },
    { id: "startup-board-governance", label: "Understanding board seat and investor governance rights and their operating implications" },
    { id: "startup-equity-vesting-mechanics", label: "Applying vesting schedules, cliffs, and acceleration mechanics to equity decisions" },
    { id: "startup-cofounder-dispute-resolution", label: "Resolving co-founder conflicts over equity, role, or company direction" },
    { id: "startup-cap-table-management", label: "Managing cap table dilution and equity allocation across rounds and disputes" },
    { id: "startup-down-round-mechanics", label: "Navigating a down round — anti-dilution provisions and investor/employee impact" },
    { id: "startup-liquidation-preference-waterfall", label: "Modeling payout waterfalls under liquidation preferences for different exit scenarios" },
    { id: "startup-exit-options-comparison", label: "Comparing acquihire, strategic sale, and shutdown options against fiduciary duty" },
    { id: "startup-key-person-retention", label: "Designing retention grants and refresh equity to manage key-person flight risk" },
    { id: "startup-bridge-financing-mechanics", label: "Structuring bridge financing (convertible notes, caps, discounts) vs. cutting costs" },
    { id: "startup-competitive-moat-analysis", label: "Identifying defensible advantages against a better-funded competitor" },
    { id: "startup-resource-allocation-prioritization", label: "Allocating scarce engineering/sales resources across competing opportunities" },
    { id: "startup-business-model-transition", label: "Managing a pricing/revenue model transition (e.g., one-time to subscription)" },
    { id: "startup-cohort-retention-analysis", label: "Using cohort and net-revenue-retention data to explain noisy growth metrics" },
    { id: "startup-legal-formation-basics", label: "Getting startup legal formation basics right — incorporation, IP assignment, 83(b), QSBS" },
  ],
  "business/Sales & Business Development": [
    { id: "sales-churn-root-cause-diagnosis", label: "Diagnosing the true root cause of customer churn before designing a response" },
    { id: "sales-win-back-offer-design", label: "Designing a proportionate win-back offer without over-conceding" },
    { id: "sales-revenue-concentration-risk", label: "Recognizing and managing customer/account revenue concentration risk" },
    { id: "sales-comp-plan-design", label: "Designing sales compensation to balance acquisition, retention, and expansion incentives" },
    { id: "sales-discount-governance", label: "Managing discount authority and precedent to protect margin and pricing integrity" },
    { id: "sales-value-based-selling", label: "Trading value (bundling, multi-year terms) instead of defaulting to price concessions" },
    { id: "sales-channel-conflict-management", label: "Managing direct-vs-reseller channel conflict with clear rules of engagement" },
    { id: "sales-channel-vs-direct-tradeoff", label: "Deciding between a partner channel and a direct build for market entry" },
    { id: "sales-bid-no-bid-decision-analysis", label: "Running an expected-value bid/no-bid analysis for large deal pursuits" },
    { id: "sales-deal-stuck-in-procurement", label: "Unsticking a deal stalled in legal/procurement without souring the relationship" },
    { id: "sales-pipeline-forecasting", label: "Building disciplined, evidence-based sales forecasts (commit/best-case/pipeline)" },
    { id: "sales-pipeline-hygiene-qualification", label: "Applying deal qualification discipline (MEDDIC/BANT) to avoid sandbagging or overcommitting" },
    { id: "sales-new-market-entry-gtm", label: "Adapting the sales motion, timeline, and investment for entry into a new vertical" },
    { id: "sales-model-segmentation", label: "Segmenting sales coverage model (inside vs. field) by deal size or account tier" },
    { id: "sales-win-loss-analysis", label: "Using win-loss analysis to diagnose competitive sales performance" },
    { id: "sales-key-rep-departure-management", label: "Stabilizing accounts and assessing legal options after a key rep's departure" },
    { id: "sales-talent-retention", label: "Proactively managing sales talent retention risk tied to compensation and culture" },
    { id: "sales-cross-sell-expansion-strategy", label: "Building and executing an account expansion/upsell play, including multi-threading" },
  ],
  "business/Supply Chain & Logistics": [
    { id: "supplychain-total-landed-cost", label: "Modeling total landed cost (tariffs, freight, carrying cost, lead-time risk) instead of comparing unit cost alone" },
    { id: "supplychain-reshoring-nearshoring", label: "Evaluating reshoring, nearshoring, offshoring, and hybrid dual-network sourcing trade-offs" },
    { id: "supplychain-supplier-ecosystem-development", label: "Recognizing supplier ecosystem development and qualification lead time as the real constraint on sourcing timelines" },
    { id: "supplychain-last-mile-unit-economics", label: "Diagnosing last-mile delivery cost drivers and segmenting contribution margin by customer/zone/SKU" },
    { id: "supplychain-disruption-triage", label: "SKU- or ABC-based triage of what to expedite, reroute, or delay during a supply disruption" },
    { id: "supplychain-concentration-risk", label: "Recognizing over-reliance on a single port, carrier, supplier, or customer as a structural risk" },
    { id: "supplychain-demand-forecasting-methods", label: "Distinguishing statistical forecasting from demand sensing and scenario planning for volatile launches" },
    { id: "supplychain-sop-process", label: "Sales and operations planning (S&OP) as the cross-functional link between demand, supply, and finance" },
    { id: "supplychain-safety-stock-policy", label: "Setting safety stock and buffer policy based on demand variability and service-level targets" },
    { id: "supplychain-bullwhip-effect", label: "Recognizing how demand variability amplifies upstream through the supply chain (bullwhip effect)" },
    { id: "supplychain-freight-contract-structuring", label: "Structuring freight contracts (fuel escalators, committed volume agreements) to manage cost volatility" },
    { id: "supplychain-3pl-vendor-risk", label: "Assessing 3PL/vendor financial health and structuring phased dual-run migration during vendor failure" },
    { id: "supplychain-business-continuity", label: "Building redundancy and business continuity plans against single points of failure in logistics networks" },
    { id: "supplychain-automation-capex-payback", label: "Evaluating warehouse automation capital investment payback against realistic implementation disruption" },
    { id: "supplychain-workforce-transition-automation", label: "Managing workforce transition (attrition, retraining, union relations) when automating logistics operations" },
    { id: "supplychain-regulated-cold-chain", label: "Applying regulatory compliance protocols (GDP, temperature excursion, release criteria) in regulated distribution" },
    { id: "supplychain-tariff-engineering", label: "Using legal tariff engineering and country-of-origin strategies as a lever against sourcing cost shocks" },
    { id: "supplychain-price-elasticity-passthrough", label: "Modeling price elasticity to decide how much cost increase to pass through versus absorb" },
    { id: "supplychain-supplier-social-compliance", label: "Enforcing supplier code-of-conduct violations via corrective action plans and responsible exit, not abrupt termination" },
    { id: "supplychain-inventory-obsolescence-mgmt", label: "Managing excess and obsolete inventory disposition and root-causing the planning failure behind it" },
    { id: "supplychain-network-design-cog", label: "Using center-of-gravity/network optimization analysis aligned to the full customer base, not one account" },
    { id: "supplychain-reverse-logistics", label: "Designing reverse logistics and returns disposition (grading, refurbishment, liquidation) as its own discipline" },
  ],
  "business/IT & Technology Management": [
    { id: "it-legacy-migration-risk", label: "Sequencing legacy core system replacement (phased/strangler-fig) while managing key-person/bus-factor risk" },
    { id: "it-vendor-lockin", label: "Recognizing vendor lock-in depth and using credible switching-cost leverage in renewal negotiations" },
    { id: "it-tco-analysis", label: "Building multi-year total cost of ownership comparisons across build/buy/vendor alternatives" },
    { id: "it-build-vs-buy", label: "Applying a core-vs-context framework to build-versus-buy technology decisions" },
    { id: "it-opportunity-cost-eng", label: "Accounting for the opportunity cost of engineering time in technology investment decisions" },
    { id: "it-ai-use-case-prioritization", label: "Prioritizing AI/technology initiatives on value versus feasibility rather than hype or visibility" },
    { id: "it-ai-governance-bias", label: "Managing algorithmic bias, model governance, and human-in-the-loop design for high-stakes automation" },
    { id: "it-shadow-it-risk", label: "Detecting and governing shadow IT without driving unsanctioned tool use further underground" },
    { id: "it-breach-notification", label: "Executing breach response and regulatory notification obligations under statutory time pressure" },
    { id: "it-finops-cost-discipline", label: "Distinguishing quick-win waste elimination from structural cost/architecture change, and institutionalizing FinOps accountability" },
    { id: "it-erp-phase-gate", label: "Defining objective go/no-go phase-gate criteria to distinguish normal stabilization from design failure" },
    { id: "it-change-management-adoption", label: "Managing change management and user adoption to prevent workaround habits from undermining a new system" },
    { id: "it-vendor-accountability", label: "Holding implementation and outsourcing partners accountable to contracted milestones rather than reassurance" },
    { id: "it-technical-debt-quantification", label: "Quantifying technical debt's business cost (velocity loss, churn) to make trade-offs data-driven" },
    { id: "it-sustainable-capacity-allocation", label: "Allocating sustained ongoing capacity, not a one-time freeze, to debt reduction and quality work" },
    { id: "it-outsourcing-governance", label: "Establishing oversight models (embedded leads, architecture review, code review gates) for outsourced development" },
    { id: "it-cyber-risk-quantification", label: "Quantifying cyber risk in financial terms (e.g., FAIR) to justify security investment against other capital priorities" },
    { id: "it-regulatory-compliance-exposure", label: "Assessing sector-specific regulatory exposure (e.g., HIPAA) created by security or technology failures" },
    { id: "it-best-of-breed-vs-suite", label: "Weighing best-of-breed functionality against the integration and data-consistency cost of platform consolidation" },
    { id: "it-centralized-vs-federated-governance", label: "Designing IT governance operating models (centralized, federated, hybrid hub-and-spoke)" },
    { id: "it-data-privacy-compliance", label: "Navigating data privacy regulatory obligations (GDPR/CCPA) distinct from security breach notification alone" },
    { id: "it-disaster-recovery-planning", label: "Designing backup and disaster recovery architecture around recovery time/point objectives (RTO/RPO)" },
  ],
  "business/Manufacturing & Production": [
    { id: "mfg-automation-roi-payback", label: "Evaluating automation capital investment payback/NPV against realistic disruption and ramp-up costs" },
    { id: "mfg-workforce-transition-automation", label: "Managing workforce transition (attrition, retraining, redeployment) when automation displaces jobs" },
    { id: "mfg-community-labor-relations", label: "Managing community, political, and labor relationship impact of major operational decisions" },
    { id: "mfg-root-cause-analysis", label: "Applying root cause methodologies (5 Whys, fishbone, SPC) to diagnose quality or compliance failures" },
    { id: "mfg-recall-decision-criteria", label: "Deciding when field-failure evidence justifies proactive notification or recall before root cause is fully certain" },
    { id: "mfg-spc-tolerance-drift", label: "Using statistical process control to detect and prevent tolerance drift introduced by process changes" },
    { id: "mfg-capacity-planning-uncertainty", label: "Planning capacity investment under uncertain or unconfirmed demand growth" },
    { id: "mfg-make-vs-buy-contract-mfg", label: "Weighing owned capacity expansion against contract manufacturing/outsourcing trade-offs" },
    { id: "mfg-downtime-cost-analysis", label: "Quantifying unplanned downtime cost to justify expedited repair and recovery spend" },
    { id: "mfg-preventive-maintenance", label: "Using preventive/predictive maintenance and redundancy planning to reduce single-line dependency risk" },
    { id: "mfg-environmental-self-disclosure", label: "Deciding to proactively self-report regulatory/environmental violations rather than remediate quietly first" },
    { id: "mfg-jit-vs-buffer-resilience", label: "Balancing just-in-time efficiency against buffer/resilience inventory strategy, targeted by input criticality" },
    { id: "mfg-facility-relocation-risk", label: "Assessing facility relocation and site-selection trade-offs including workforce retention risk" },
    { id: "mfg-phased-transition-execution", label: "Using phased/parallel-run execution to de-risk major operational transitions" },
    { id: "mfg-commodity-hedging", label: "Managing commodity input price volatility via hedging, contract renegotiation, or reformulation" },
    { id: "mfg-cost-passthrough-contracts", label: "Negotiating index-based cost pass-through clauses into customer contracts to manage margin volatility" },
    { id: "mfg-osha-safety-authority", label: "Exercising stop-work/safety-first production halt authority independent of delivery pressure" },
    { id: "mfg-machine-guarding-compliance", label: "Applying machine guarding/lockout-tagout standards and systemic-versus-isolated incident investigation" },
    { id: "mfg-sustainability-capex-roi", label: "Evaluating green/sustainability capital investment against payback period and the strategic risk of inaction" },
    { id: "mfg-labor-relations-cba", label: "Navigating collective bargaining agreement consultation clauses and interest-based bargaining" },
    { id: "mfg-sku-rationalization-complexity-costing", label: "Using activity-based costing and portfolio segmentation (Pareto) to rationalize low-value, high-complexity SKUs" },
    { id: "mfg-lean-continuous-improvement", label: "Sustaining lean/continuous improvement (Kaizen, 5S, value stream mapping) beyond initial improvement events" },
  ],
  "business/Product Management & Innovation": [
    { id: "product-prioritization-frameworks", label: "Arbitrating competing roadmap demands (sales vs. engineering, vocal customers) with structured frameworks like RICE or opportunity-cost quantification instead of authority or volume of asks" },
    { id: "product-tech-debt-tradeoff", label: "Quantifying the probability and cost of deferred technical debt or infrastructure risk against near-term revenue capture" },
    { id: "product-loss-aversion-deprecation", label: "Distinguishing stated customer attachment/loss aversion from revealed usage data when deciding to deprecate a feature" },
    { id: "product-mvp-expectation-setting", label: "Managing early-adopter expectations for a deliberately stripped-down MVP and triaging feedback signal from noise" },
    { id: "product-innovation-governance", label: "Designing stage-gate funding and business-unit ownership so innovation-lab prototypes actually reach production" },
    { id: "product-sustainable-moat", label: "Identifying durable competitive advantage (proprietary data, workflow lock-in, network effects) versus features that are easily cloned" },
    { id: "product-accessibility-compliance", label: "Treating accessibility and regulatory compliance (e.g., WCAG) as a launch floor, not a negotiable scope item, under deadline pressure" },
    { id: "product-incident-disclosure", label: "Scoping and timing user and regulatory disclosure for a data or privacy incident across jurisdictions" },
    { id: "product-lifecycle-sunset", label: "Managing end-of-life/sunset of a legacy product line, including migration economics and reference-customer value" },
    { id: "product-experimentation-safety", label: "Using canary releases, feature flags, and blast-radius limits so experimentation velocity coexists with production stability and SLAs" },
    { id: "product-statistical-rigor", label: "Holding firm on statistically significant experiment results against pressure to override them for stakeholder optics (HiPPO bias)" },
    { id: "product-segment-prioritization", label: "Weighing a vocal power-user minority's demands against mainstream-user and onboarding economics using data, not volume of feedback" },
    { id: "product-build-vs-partner", label: "Evaluating build-vs-buy-vs-partner tradeoffs, including channel conflict and strategic partnership value beyond direct cost savings" },
    { id: "product-cross-functional-roadmap-governance", label: "Running a transparent, criteria-based roadmap decision process across sales, engineering, and leadership rather than resolving standoffs by seniority" },
    { id: "product-jtbd-discovery", label: "Using jobs-to-be-done and customer discovery to validate a real underlying problem before committing engineering investment" },
    { id: "product-pricing-monetization", label: "Structuring pricing and packaging so the monetization model aligns with delivered value and validated willingness to pay" },
    { id: "product-vision-narrative", label: "Crafting and defending a product vision/strategy narrative that gives roadmap tradeoffs a consistent rationale" },
  ],
  "business/Customer Experience": [
    { id: "cx-effort-score", label: "Using Customer Effort Score to diagnose experience friction that satisfaction scores alone miss" },
    { id: "cx-vendor-tco", label: "Evaluating outsourced/BPO vendor quality problems via total cost of ownership rather than headline cost savings alone" },
    { id: "cx-privacy-creepy-line", label: "Recognizing when personalization or data use crosses the 'creepy line' of user comfort beyond legal consent minimums" },
    { id: "cx-crisis-response-sequencing", label: "Sequencing individual customer resolution against public crisis communication under reputational time pressure" },
    { id: "cx-service-recovery-paradox", label: "Applying the service recovery paradox to convert a visible failure into stronger loyalty through genuine remediation" },
    { id: "cx-nps-driver-analysis", label: "Segmenting and root-causing NPS/CSAT movement by cohort instead of assuming feature-shipping volume equals satisfaction" },
    { id: "cx-kano-model", label: "Applying the Kano model to distinguish must-have fixes from bloat-inducing nice-to-haves in a feedback-driven backlog" },
    { id: "cx-net-cost-to-serve", label: "Modeling net cost-to-serve and self-service deflection savings inclusive of downstream churn cost, not gross savings" },
    { id: "cx-escalation-path-design", label: "Designing frictionless escalation from self-service or bot to a human for cases automation is structurally unsuited to resolve" },
    { id: "cx-loyalty-economics", label: "Managing loyalty-program redesign economics against grandfathering and legacy-member retention risk" },
    { id: "cx-clv-segmentation", label: "Using customer lifetime value segmentation to triage response and retention effort toward the highest-value accounts" },
    { id: "cx-surge-capacity-planning", label: "Forecasting and planning support capacity for foreseeable peak or surge demand" },
    { id: "cx-ticket-triage-severity", label: "Triaging a support queue by severity and business impact rather than first-in-first-out during a capacity crisis" },
    { id: "cx-activation-time-to-value", label: "Defining and owning time-to-value/activation metrics to catch onboarding failure before it becomes silent churn" },
    { id: "cx-journey-mapping", label: "Using customer journey mapping to diagnose systemic, cross-channel experience breakdowns" },
    { id: "cx-service-blueprinting", label: "Using service blueprinting to redesign a multi-touchpoint process end-to-end, including backstage systems and ownership" },
    { id: "cx-dsar-compliance", label: "Standing up a compliant data subject access/deletion request intake, verification, and fulfillment process" },
    { id: "cx-executive-sponsorship", label: "Deploying executive sponsorship and honest timelines as a relationship-repair lever for an at-risk key account" },
    { id: "cx-frontline-empowerment", label: "Connecting frontline employee experience, morale, and tooling to downstream customer experience outcomes" },
    { id: "cx-voice-of-customer-program", label: "Designing an ongoing, multi-channel voice-of-customer program with closed-loop follow-up, not one-off surveys" },
  ],
  "business/HR & Talent Management": [
    { id: "talent-pay-equity-audit", label: "Conducting and remediating pay equity audits, including root-cause analysis across hiring, promotion, and negotiation" },
    { id: "talent-comp-benchmarking", label: "Compensation benchmarking and managing internal pay compression against external market pressure" },
    { id: "talent-evp-design", label: "Building or adjusting employer value proposition when compensation alone can't win a competitive talent market" },
    { id: "talent-build-buy-partner-talent", label: "Evaluating build-vs-buy-vs-partner alternatives (contractors, acquihire, upskilling) when direct hiring stalls" },
    { id: "talent-promotion-governance", label: "Designing documented, calibrated promotion criteria that prevent and can defend against favoritism perception" },
    { id: "talent-counter-offer-policy", label: "Applying compensation-philosophy consistency to counter-offer decisions and their second-order equity effects" },
    { id: "talent-key-person-risk", label: "Identifying and mitigating key-person/bus-factor risk independent of whether the individual stays or leaves" },
    { id: "talent-succession-planning", label: "Building a leadership pipeline (9-box, HiPo development) instead of defaulting to repeated external hiring" },
    { id: "talent-pip-legal-risk", label: "Recognizing retaliation/discrimination risk patterns in performance-management timing relative to protected leave or accommodation requests" },
    { id: "talent-psych-safety-investigation", label: "Investigating psychological-safety or toxic-manager complaints with corroborating evidence despite stakeholder skepticism" },
    { id: "talent-layoff-survivor-trust", label: "Managing layoff survivor syndrome and rebuilding trust without false reassurance" },
    { id: "talent-accommodation-policy", label: "Designing consistent, legally sound accommodation/exception policy to avoid precedent and fairness risk" },
    { id: "talent-founder-succession", label: "Separating emergency from long-term CEO/founder succession planning under governance and investor pressure" },
    { id: "talent-worker-classification", label: "Assessing independent-contractor misclassification risk (ABC/IRS tests) and planning remediation" },
    { id: "talent-whistleblower-investigation", label: "Running independent, conflict-free investigations into senior-leader misconduct allegations with witness protection" },
    { id: "talent-engagement-survey-action", label: "Turning engagement-survey data into credible action planning despite stakeholder pushback" },
    { id: "talent-onboarding-newhire", label: "Designing a structured new-hire onboarding plan (e.g., 30-60-90) that reduces early attrition" },
    { id: "talent-inclusive-hiring-bias", label: "Structuring interview panels and scorecards to reduce bias and adverse-impact exposure in hiring decisions" },
  ],
  "business/International & Global Business": [
    { id: "intl-entry-mode-selection", label: "Choosing a market-entry mode (export, license, JV, wholly-owned subsidiary) based on control-risk-speed tradeoffs" },
    { id: "intl-jv-structuring", label: "Structuring a joint venture to substitute contractual/technical protections for equity control when local law caps foreign ownership" },
    { id: "intl-jv-governance-disputes", label: "Governing an ongoing JV relationship: audit rights, information asymmetry, dispute escalation sequencing, exit/buy-sell clauses" },
    { id: "intl-currency-exposure-hedging", label: "Distinguishing transaction, translation, and economic FX exposure and selecting appropriate hedging instruments" },
    { id: "intl-capital-controls-repatriation", label: "Managing trapped cash and selecting legitimate repatriation channels under capital controls" },
    { id: "intl-transfer-pricing", label: "Structuring arm's-length intercompany transactions (royalties, management fees, cost-sharing) for tax-compliant cash movement" },
    { id: "intl-cross-border-labor-law", label: "Navigating divergent labor/termination regimes (works councils, social plans, at-will vs. cause-based, statutory severance)" },
    { id: "intl-expat-selection-adjustment", label: "Selecting and supporting expatriate leaders, recognizing expatriate failure patterns and adjustment breakdown" },
    { id: "intl-cultural-intelligence-communication", label: "Managing high-context vs. low-context communication norms and psychological safety across distributed global teams" },
    { id: "intl-cultural-due-diligence-marketing", label: "Running cultural sensitivity review on marketing/product localization before launch, and governance to make regional vetoes stick" },
    { id: "intl-standardization-vs-adaptation", label: "Applying the integration-responsiveness framework to decide what must be globally standardized vs. locally adapted" },
    { id: "intl-anti-corruption-compliance", label: "Applying FCPA/anti-bribery rules including third-party/agent liability and the narrow facilitation-payment exception" },
    { id: "intl-export-controls-sanctions", label: "Complying with export controls and sanctions, including why third-country routing is evasion, not a workaround" },
    { id: "intl-country-risk-site-selection", label: "Assessing political/regulatory risk and talent/capital access tradeoffs for regional HQ or facility site selection" },
    { id: "intl-trade-policy-tariffs", label: "Responding to tariff and trade-policy shifts: pass-through vs. absorption decisions and sourcing diversification timelines" },
    { id: "intl-staffing-strategy-eprg", label: "Choosing an international staffing orientation (ethnocentric/polycentric/geocentric) appropriate to the operation's needs" },
    { id: "intl-cross-border-ma-integration", label: "Planning post-merger integration sequencing and key-talent retention in a cross-border acquisition" },
    { id: "intl-global-pricing-gray-market", label: "Managing cross-market price differentials to avoid triggering gray-market/parallel-import arbitrage" },
  ],
  "business/Corporate Governance & Risk": [
    { id: "gov-conflict-of-interest-disclosure", label: "Evaluating director conflict-of-interest disclosure timing and the difference between vote recusal and full exclusion from deliberation" },
    { id: "gov-related-party-transaction-review", label: "Distinguishing disclosure of a related-party transaction from substantive independent/arm's-length review of its fairness" },
    { id: "gov-duty-of-loyalty-fiduciary", label: "Applying fiduciary duty of loyalty/care and the business judgment rule to interested-party decisions" },
    { id: "gov-activist-defense-strategy", label: "Evaluating an activist investor campaign on its merits and choosing negotiated settlement vs. proxy fight" },
    { id: "gov-takeover-defenses", label: "Understanding takeover and shareholder-rights defensive measures (poison pills, staggered boards) and their limits" },
    { id: "gov-whistleblower-protection", label: "Designing independent, non-retaliatory investigation protocols under whistleblower protection law" },
    { id: "gov-esg-disclosure-integrity", label: "Assessing ESG/sustainability disclosure for materiality and greenwashing risk rather than favorable-metric selection" },
    { id: "gov-ceo-succession-planning", label: "Running CEO succession planning: capability-gap diagnosis, internal vs. external tradeoffs, key-person retention risk" },
    { id: "gov-board-committee-authority", label: "Understanding board committee structure (audit, risk, comp, nominating) and its independent oversight authority" },
    { id: "gov-concentration-risk-oversight", label: "Overseeing concentration risk against regulatory guidance thresholds rather than relying on lagging asset-quality metrics" },
    { id: "gov-three-lines-of-defense", label: "Applying the three-lines-of-defense risk governance model and documenting dissent when risk warnings are overruled" },
    { id: "gov-insider-trading-compliance", label: "Applying insider trading law, 10b5-1 plan integrity/amendment scrutiny, and MNPI-timeline reconstruction" },
    { id: "gov-shareholder-value-restructuring", label: "Evaluating breakup/spin-off shareholder proposals using conglomerate discount and sum-of-the-parts analysis" },
    { id: "gov-climate-risk-disclosure", label: "Applying materiality standards to climate-related financial risk disclosure decisions" },
    { id: "gov-executive-comp-clawback", label: "Applying the mandatory, no-fault executive compensation clawback standard under Dodd-Frank/SEC Rule 10D-1" },
    { id: "gov-say-on-pay-comp-design", label: "Designing and benchmarking executive compensation under say-on-pay and investor scrutiny" },
    { id: "gov-cyber-oversight-caremark", label: "Applying the board's Caremark duty of oversight to cybersecurity and compliance risk reporting" },
    { id: "gov-incident-escalation-protocol", label: "Ensuring internal escalation protocols get material incidents to the board/legal, and remediating breach-notification failures" },
    { id: "gov-board-independence-composition", label: "Assessing whether board composition provides genuine independence from management, not just nominal outside directors" },
    { id: "gov-shareholder-derivative-litigation", label: "Understanding demand futility doctrine in shareholder derivative suits and D&O liability exposure tied to board independence" },
  ],
  "business/Retail & E-commerce": [
    { id: "retail-omnichannel-attribution", label: "Building market-level/halo-effect attribution instead of relying on single-channel store P&L for structural decisions" },
    { id: "retail-fulfillment-network-design", label: "Designing store/fulfillment network roles (ship-from-store, BOPIS nodes) as a factor independent of raw sales profitability" },
    { id: "retail-inventory-sync-oversell", label: "Preventing and resolving real-time inventory sync failures that cause overselling during demand spikes" },
    { id: "retail-demand-forecasting-promotions", label: "Forecasting demand and capacity for promotional/viral events, including social-driven traffic multipliers" },
    { id: "retail-platform-dependency-risk", label: "Managing marketplace/platform channel concentration risk and assessing real negotiating leverage against a dominant platform" },
    { id: "retail-dtc-channel-investment", label: "Building a funded, milestone-based direct-to-consumer channel to reduce platform dependency and retain customer data" },
    { id: "retail-marketplace-liability-counterfeit", label: "Assessing a marketplace's secondary/contributory liability exposure for counterfeit third-party listings" },
    { id: "retail-seller-vetting-moderation", label: "Balancing proactive seller vetting/content moderation investment against seller-growth and onboarding-speed metrics" },
    { id: "retail-unit-economics-contribution-margin", label: "Building fully-loaded unit economics/contribution margin analysis by channel or service tier" },
    { id: "retail-cac-ltv-subsidization", label: "Justifying (or rejecting) a loss-making service tier using CAC/LTV and retention data rather than per-order economics alone" },
    { id: "retail-ab-testing-scale-validity", label: "Diagnosing why an A/B-tested change fails at full scale (segment heterogeneity, Simpson's paradox, sample power)" },
    { id: "retail-incident-rollback-decisioning", label: "Deciding between full rollback, partial fix, and staged diagnosis when a live change is actively costing revenue" },
    { id: "retail-private-label-strategy", label: "Weighing private-label margin expansion against brand-equity/consumer-trust limits in specific categories" },
    { id: "retail-vendor-trade-promotion-leverage", label: "Netting projected margin gains against realistic vendor retaliation (co-op funding, shelf support) in category management" },
    { id: "retail-supply-disruption-allocation", label: "Allocating constrained supply across channels/segments and qualifying backup suppliers under time pressure" },
    { id: "retail-dynamic-pricing-fairness", label: "Managing algorithmic/dynamic pricing transparency and perceived price-discrimination backlash" },
    { id: "retail-return-fraud-policy-design", label: "Designing segmented, abuse-targeted return policy enforcement instead of blanket policy tightening" },
    { id: "retail-pilot-to-scale-validation", label: "Validating whether a small pilot's conversion/engagement results will hold before committing to full-scale investment" },
    { id: "retail-experiential-differentiation", label: "Using service/experience differentiation to convert showrooming behavior into captured sales" },
    { id: "retail-loyalty-program-economics", label: "Managing loyalty/points-liability accounting (breakage rate assumptions) against promotional redemption-rate drift" },
    { id: "retail-markdown-clearance-optimization", label: "Designing markdown cadence and open-to-buy planning to avoid training customers to wait for discounts" },
  ],
};

export function fundamentalsKey(profession: string, category: string): string {
  return `${profession}/${category}`;
}

export function getFundamentals(profession: string, category: string): Fundamental[] {
  return FUNDAMENTALS[fundamentalsKey(profession, category)] ?? [];
}

export function getFundamentalLabel(profession: string, category: string, id: string): string {
  return getFundamentals(profession, category).find((f) => f.id === id)?.label ?? id;
}
