import { NextRequest, NextResponse } from "next/server";
import { generateScript } from "@/lib/generateScript";
import { geminiErrorResponse } from "@/lib/gemini";
import { getLanguage, toLanguageCode } from "@/lib/languages";
import { requireApiUser } from "@/lib/requireUser";
import { checkRateLimit } from "@/lib/rateLimit";

const MAX_INPUT_CHARS = 4000;

/**
 * POST /api/generate-script
 * Accepts { input: string } (a topic, rough notes, or a draft) and returns
 * a polished, speakable script generated by Gemini (mocked if
 * GEMINI_API_KEY isn't set).
 */
export async function POST(req: NextRequest) {
  const gate = await requireApiUser();
  if (gate instanceof NextResponse) return gate;

  if (!(await checkRateLimit(String(gate.id)))) {
    return NextResponse.json({ error: "Too many requests. Please slow down." }, { status: 429 });
  }

  let body: { input?: string; language?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Expected JSON body." }, { status: 400 });
  }

  const input = body.input?.trim();
  if (!input) {
    return NextResponse.json({ error: "Missing 'input' text." }, { status: 400 });
  }
  if (input.length > MAX_INPUT_CHARS) {
    return NextResponse.json({ error: "Input is too long." }, { status: 413 });
  }

  try {
    const result = await generateScript(input, getLanguage(toLanguageCode(body.language)).name);
    return NextResponse.json(result);
  } catch (err) {
    return geminiErrorResponse(err, "Script generation failed.");
  }
}
