import { NextRequest, NextResponse } from "next/server";
import { generateScript } from "@/lib/generateScript";

/**
 * POST /api/generate-script
 * Accepts { input: string } (a topic, rough notes, or a draft) and returns
 * a polished, speakable script generated by Gemini (mocked if
 * GEMINI_API_KEY isn't set).
 */
export async function POST(req: NextRequest) {
  let body: { input?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Expected JSON body." }, { status: 400 });
  }

  const input = body.input?.trim();
  if (!input) {
    return NextResponse.json({ error: "Missing 'input' text." }, { status: 400 });
  }

  try {
    const result = await generateScript(input);
    return NextResponse.json(result);
  } catch (err) {
    console.error("generate-script failed:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Script generation failed." },
      { status: 500 },
    );
  }
}
